# Generated by Django 4.2.30 on 2026-05-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('sport_type', models.CharField(choices=[('padel', 'Pádel'), ('tenis', 'Tenis'), ('futbol_sala', 'Fútbol Sala'), ('badminton', 'Bádminton'), ('squash', 'Squash'), ('baloncesto', 'Baloncesto'), ('otro', 'Otro')], max_length=20, verbose_name='deporte')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='capacidad (jugadores)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio por hora (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
                'ordering': ['sport_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=20, verbose_name='estado')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='es recurrente')),
                ('recurrence_type', models.CharField(choices=[('none', 'Sin repetición'), ('weekly', 'Semanal')], default='none', max_length=20, verbose_name='tipo de recurrencia')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='fin de recurrencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservas.resource', verbose_name='pista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora apertura')),
                ('end_time', models.TimeField(verbose_name='hora cierre')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='reservas.resource', verbose_name='pista')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('resource', 'day_of_week')},
            },
        ),
    ]
